url: "https://recap.build"
baseurl: ""
title: "Recap"
plugins:
  - jekyll-inline-svg
  - jekyll-postcss
  - jekyll-redirect-from
postcss:
  cache: false
svg:
  optimize: true
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
