url: "https://recap.build"
title: "Recap"
description: "Read schemas from web service, databases, and schema registries in a standard format."
theme: just-the-docs

logo: "/assets/images/recap-logo.png"
color_scheme: recap
aux_links:
  "<i class=\"social-logo fa-brands fa-github\"></i>":
    - "//github.com/recap-build/recap"
plugins:
  - jekyll-redirect-from
